### ISSUE TITLE
Checklist for paper

### ISSUE THREAD

**Issue by luiarthur** [luiarthur/cytof5#22]
- Sim N500
    - [X] VI
        - [X] K=5, 10, 30
        - [X] batchsize=100, 500, 2000
    - [X] MCMC
    - [X] miss mech sensitivity
    - [X] FlowSOM
- Sim N5000
    - [X] VI
        - [X] K=5, 10, 30
        - [X] batchsize=100, 500, 2000
    - [X] MCMC
    - [X] miss mech sensitivity
    - [X] FlowSOM
- CB
    - [ ] VI
        - [ ] K=5, 10, 30
        - [ ] batchsize=100, 500, 2000
    - [X] MCMC
    - [ ] miss mech sensitivity
        - [ ] yquant: (0%, 20%, 40%), pbounds: (5%, 80%, 5%)
        - [ ] yquant: (0%, 15%, 30%), pbounds: (5%, 80%, 5%)
    - [x] FlowSOM
- new K selection method to implement
    - ![K-selection-method](https://user-images.githubusercontent.com/5297817/57406043-bb1f4d00-7194-11e9-9146-f11be25410e0.png)
